# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  docuwareConnector:
    # The DocuWare default configuration.
    defaultConfig:
      # The Id of this configuration. It is only used to invalidate any cached connection based on this (and inherited) configuration.
      configId: ""
      # The URL of the server, including the platform part (compare to Postman collection), eg. https://acme.docuware.cloud/DocuWare/Platform
      url: ""
      # The type of authorization grant to provide.
      # [enum: password, trusted, dwtoken]
      grantType: ""
      # The username used for authenticating to DocuWare.
      username: ""
      # The password used for authenticating to DocuWare.
      #[password]
      password: ${decrypt:}
      # This property sets the maximum time (in milliseconds) that the client will wait when attempting to establish a connection with the server.
      # The value MUST be an instance convertible to Integer. A value of zero (0) is equivalent to an interval of infinity.
      connectTimeout: "0"
      # This property defines the maximum number of characters of an entity that will be logged.
      loggingEntityMaxSize: "8192"
      # The password used for encrypting parameters of embedded urls (set in Configurations/Organization Settings/Security)
      #[password]
      integrationPassphrase: ""
