# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  docuwareConnector:
    defaultConfig:
      configId: "1"
      url: https://presentationvm/docuware/platform
      grantType: password
      username: admin
      #[password]
      password: ${decrypt:k1GmwSEiJtUbRb2q6CZ9QQ==}
    demoTrustedUser:
      configId: "1"
      inherit: defaultConfig
      grantType: trusted
    presales:
      configId: "1"
      inherit: defaultConfig
      url: https://presales-axonivy.docuware.cloud/docuware/platform
      grantType: password
      username: presales.axonivy
      #[password]
      password: ${decrypt:lPij4j2mkTBwgl1pfnwjsA==}
    host: ""
    username: ""
    password: ""
    organization: ""
    fileCabinetId: ""
