# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
#
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
  docuwareConnector:
    # Default configuration for a single, technical user.
    defaultConfig:
      configId: "1"
      url: "https://put.here.your.url/DocuWare/Platform"
      grantType: "password"
      username: "REMOVED"
      #[password]
      password: "REMOVED"
      connectTimeout: "10000"
      readTimeout: "10000"
      integrationPassphrase: "REMOVED"
    # Work with different users authenticated by a trusted user (remove this section if you do not have access to an instance supporting this).
    trustedUser:
      configId: "1"
      inherit: defaultConfig
      grantType: "trusted"
      username: "REMOVED"
      #[password]
      password: "REMOVED"
      impersonateUser: ^ivy:system=admin,anonymous=admin
    # Work with a DW Token (remove this section if you do not have access to an instance supporting this).
    dwToken:
      configId: "1"
      url: "https://put.here.your.url/DocuWare/Platform"
      grantType: "dwtoken"
      dwToken: "^session"
  # Variables used by the demo.
  docuwareWorkflow:
    fileCabinetId: ""
    dialogId: ""
